[IV-23-24] Lenguaje decidido
manuelvico0102/easySelect pull request #7
Opened 2023-10-06 11:11 UTC by MarioGuisado

Se ha decidido usar TypeScript closes #6

2023-10-17 10:10 UTC, MarioGuisado commented
@manuelvico0102 Listo para revisión.

2023-10-17 10:13 UTC, manuelvico0102 approved these changes

2023-10-17 10:18 UTC, manuelvico0102 commented
@JJ listo para revisión

2023-10-17 10:26 UTC, JJ commented
Me parece *muy* raro que no haya hecho falta ninguna revisión. ¿De veras lo ha tenido todo correcto a la primera? En cualquier entorno profesional, los PRs que pasan sin ninguna revisión son prácticamente imposibles.

2023-10-19 08:53 UTC, manuelvico0102 reviewed
* [x]  ¿Los issues que ha planteado la persona son efectivamente problemas y
evidencian comprensión de las historias de usuario? Si no es así, es mejor que
se le transmita antes de que empiece a crear cualquier código erróneo.
* [x]  ¿Has comprobado que efectivamente el compañero/a ha seguido *su* lista de
      comprobación?
* [x]  ¿El código creado es una modelización válida de las historias de usuario
      creadas por ti, y te sirve como base para programar la lógica de negocio?
Sí, he revisado el código y pienso que me puede servir para programar la lógica de negocio
* [x]  ¿El código creado sigue las mejores prácticas para el lenguaje de
      programación que hayáis consensuado, tanto en identificadores, como
      nombres de ficheros, como disposición de los diferentes ficheros en el
      repositorio? Por ejemplo, ¿todos los commits se refieren a un issue y
      aportan código para resolver el problema planteado en el mismo?
He revisado y todos los commits y se refieren a un issue, salvo uno que era una corrección de un nombre de variable.
* [x]  ¿He comprobado que el código compile, o que quien lo ha programado ha lo
ha hecho y documentado en el repositorio? Sí, lo he comprobado y compila.
* [x]  ¿He añadido el PR y todos los issues que se resuelvan en él al milestone
correspondiente, que será el primero? Sí
* [x]  ¿Cubre totalmente el milestone 0, o hará falta modelización adicional en
el objetivo 4 para poder programar la lógica de negocio?
Sí, abarca todo el milestone 0
* [x]  En resumen, ¿considero que con lo hecho puedo ponerme a trabajar
directamente en el siguiente milestone, que incluye la lógica de negocio?
Sí

2023-10-19 11:19 UTC, JJ commented
> * [x]   ¿Los issues que ha planteado la persona son efectivamente problemas y
>       evidencian comprensión de las historias de usuario? Si no es así, es mejor que
>       se le transmita antes de que empiece a crear cualquier código erróneo.

Conviene de verdad que analicéis esto, sobre todo a la luz de lo que hemos hablado hoy en clase. Te parece que #12 (Definición constructor) plantee un problema?

>     * [x]   ¿Has comprobado que efectivamente el compañero/a ha seguido _su_ lista de
>       comprobación?

Los mensajes de commit no siguen el formato estándar ni las buenas prácticas, me temo. Aunque se ha usado el formato 50+80, *los issues se tienen que mencionar en los primeros 50 caracteres*, para que sean más visibles.

>     * [x]   ¿El código creado es una modelización válida de las historias de usuario
>       creadas por ti, y te sirve como base para programar la lógica de negocio?
>       Sí, he revisado el código y pienso que me puede servir para programar la lógica de negocio

¿La descripción de la oferta la vas a incluir en la lógica de negocio?

>     * [x]   ¿El código creado sigue las mejores prácticas para el lenguaje de
>       programación que hayáis consensuado, tanto en identificadores, como
>       nombres de ficheros, como disposición de los diferentes ficheros en el
>       repositorio? Por ejemplo, ¿todos los commits se refieren a un issue y
>       aportan código para resolver el problema planteado en el mismo?
>       He revisado y todos los commits y se refieren a un issue, salvo uno que era una corrección de un nombre de variable.

¿No usa TS un fichero package.json para describirlo?
> 
>     * [x]   ¿Cubre totalmente el milestone 0, o hará falta modelización adicional en
>       el objetivo 4 para poder programar la lógica de negocio?
>       Sí, abarca todo el milestone 0

¿De dónde se extrae esa información? La lógica de negocio trata principalmente, si lo he entendido bien, de extraer información. De dónde se extrae, ¿dónde está? ¿Dónde está el issue que lo describe?
> 
>     * [x]   En resumen, ¿considero que con lo hecho puedo ponerme a trabajar
>       directamente en el siguiente milestone, que incluye la lógica de negocio?
>       Sí

¿Sin el documento del que se extrae la información?

2023-10-19 11:21 UTC, JJ requested changes
En general, creo que has cubierto bastante bien una parte del modelo, aunque has tomado una serie de decisiones que no están totalmente justificadas; el problema es que no has acabado de plantear los problemas correctamente, y eso hace que realmente falten cosas esenciales para el flujo de trabajo de la lógica de negocio.

Por favor, dale una vuelta, mira a ver qué cosas faltan, y p'alante.

2023-10-19 11:21 UTC, JJ commented on src/candidato.ts
> +    getNombre(): string {
¿En qué parte de la HU se solicita que la lógica de negocio necesite getters para todas las variables de instancia?
Una vez más, es *deuda técnica*: cosas que tendrás que modificar si hay alguna modificación de las variables de instancia.

2023-10-20 12:02 UTC, manuelvico0102 requested changes

2023-10-20 12:07 UTC, MarioGuisado commented
@manuelvico0102 Listo.

2023-10-20 12:07 UTC, manuelvico0102 approved these changes

2023-10-20 12:16 UTC, manuelvico0102 commented
@JJ listo para la revisión

2023-10-23 15:54 UTC, MarioGuisado commented
@manuelvico0102 He añadido el código que modela la extracción de información de los ficheros y la creación de los candidatos asociados.

2023-10-23 15:58 UTC, manuelvico0102 commented
Vale, yo lo veo bien, no sé si realmente la función es necesaria, en el sentido de que no sé si eso ya sería parte de la lógica de negocio. Pero yo creo que si me serviría.

2023-10-23 16:11 UTC, JJ commented
Por favor, no uséis enlaces a usuario/repo#xx. Esos commits pueden o no estar en la versión definitiva. Si aparecen en el issue 40 enlaces de 40 commits que finalmente no están en la versión definitiva, no estáis añadiendo más que ruido. Usad sólo el número, que ya aparecerá el enlace y el commit *cuando se fusione*

2023-10-23 16:21 UTC, JJ requested changes
El problema principal, aparte de las buenas prácticas, es que has incluido como código lo que debería ser parte del modelo del problema. Copilot está bien, pero sólo hace lo que le pides. Lo que tienes que aprender es a pedirle lo que sirva en la fase específica del problema en el que estés trabajando.

2023-10-23 16:21 UTC, JJ commented on src/candidato.ts
> +    private lenguajesDeProgramacion: { [lenguaje: string]: "principiante" | "intermedio" | "avanzado" };
A @manuelvico0102 ¿seguro que la forma habitual de expresar el conocimiento de un lenguaje de programación es "principiante" "intermedio" y "avanzado"? ¿Te parece una modelización correcta de esta parte del problema?

2023-10-23 16:21 UTC, JJ commented on src/candidato.ts
> +      lenguajesDeProgramacion: { [lenguaje: string]: "principiante" | "intermedio" | "avanzado" }
DRY: esto (y el de arriba) lo estás repitiendo. "Don't repeat yourself" es una buena práctica que indica que no deben repetirse los literales, sino usar un tipo para representarlo.

2023-10-23 16:21 UTC, JJ commented on src/candidato.ts
> +      disponibilidad: "baja" | "media" | "alta",
¿Qué significa una disponibilidad "media"?

2023-10-23 16:21 UTC, JJ commented on src/candidato.ts
> +      this.lenguajesDeProgramacion = lenguajesDeProgramacion;
Como te he dicho en la revisión anterior, toda esta clase sería el resultado de la lógica de negocio, difícilmente corresponde al dominio del problema, pero en todo caso, si decides modelizarlo, deberías de hacerlo de forma que *realmente* resuelvan los problemas planteados y usen la misma terminología y niveles del dominio del problema, no categorías o niveles inventados ex profeso.

2023-10-23 16:21 UTC, JJ commented on src/gestorCandidato.ts
> +    private procesarArchivo() {
En ningún momento se ha pedido que en este milestone se incluya ningún tipo de código.

2023-10-23 16:21 UTC, JJ commented on tsconfig.json
> +    /* Visit https://aka.ms/tsconfig to read more about this file */
Lo comentado es mejor que lo borréis.

2023-10-26 07:23 UTC, MarioGuisado commented
@manuelvico0102 Listo.

2023-10-26 07:27 UTC, manuelvico0102 commented
Yo lo veo bien

2023-10-26 08:00 UTC, JJ approved these changes
👍 

OK, parece que el candidato está donde tiene que estar, no le hagas caso al comentario.

2023-10-26 14:40 UTC, merged